#!/usr/bin/env bash
#configures a new Ubuntu machine to respect above requirements
#(this script will be run on the server itself)

sudo apt-get -y update
sudo apt upgrade -y
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
