#!/usr/bin/env bash
#configures nginx server to listen on port 80(short and sweet)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
