#!/usr/bin/env bash
#Displaying numbers 1 to 100
#In place of multiples of 3, display "Fizz"
#In place of multiples of 5, display "Buzz"
#If a number is multiple of both 3 and 5, display "FizzBuzz"

for (( i=1; i<=100; i++ ))
do
	if (( i%3==0 && i%5==0 ))
	then
		echo "FizzBuzz"
	elif (( i%3==0 ))
	then
		echo "Fizz"
	elif (( i%5==0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
